# config/agent/default.yaml
# The name of tools and sub-agents defined in: ./miroflow/src/miroflow/utils/prompt_utils.py and tool_utils.py
# Each sub-agent prompt is written in: mirage/apps/reorg-modular-structure/src/mirage_agent/utils/prompt_utils.py
defaults:
  - default
  - _self_

# LLM configuration for different agent types
main_agent_llm: "oai-chat-sdk_openrouter_claude-3.7-sonnet"         # Main agent uses Claude 3.7 Sonnet (temp=0.3)
sub_agent_llm: "oai-chat-sdk_openrouter_claude-3.7-sonnet"    # Sub agents use Claude 3.7 Sonnet


main_agent:
  prompt_class: MainAgentPromptBoxedAnswer
  tool_config: []
  max_turns: 20  # Maximum number of turns for main agent execution
  max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn

sub_agents:
  agent-worker:
    prompt_class: SubAgentWorkerPrompt
    tool_config:
      - tool-reading
    max_turns: 20
    max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn

o3_hint: false
o3_final_answer: false

# Message ID configuration
add_message_id: true  # Add random message ID to all messages sent to LLM

keep_tool_result: -1