# config/agent/claude03_claude_dual.yaml
# Agent configuration with Claude 3.7 Sonnet (temp=0.3) for both main and sub agents
defaults:
  - default
  - _self_

# LLM configuration for different agent types
main_agent_llm: "oai-chat-sdk_openrouter_claude-3.7-sonnet"         # Main agent uses Claude 3.7 Sonnet (temp=0.3)
sub_agent_llm: "oai-chat-sdk_openrouter_claude-3.7-sonnet"    # Sub agents use Claude 3.7 Sonnet

main_agent:
  llm: "oai-chat-sdk_openrouter_claude-3.7-sonnet"
  prompt_class: MainAgentGaiaPrompt
  tool_config:
    - tool-reasoning
  max_turns: -1  # Maximum number of turns for main agent execution
  max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn

sub_agents:
  agent-worker:
    prompt_class: SubAgentWorkerPrompt
    tool_config:
      - tool-searching
      - tool-image-video
      - tool-reading
      - tool-code
      - tool-audio
    max_turns: -1
    max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn

o3_hint: true
o3_final_answer: true  # Use O3 to extract final answer from summary

# Message ID configuration
add_message_id: true  # Add random message ID to all messages sent to LLM

keep_tool_result: -1