# config/config.yaml
defaults:
  - llm: claude_openrouter
  - agent: base_agent_1
  - benchmark: gaia-validation
  # disable hydra logging
  # see https://github.com/facebookresearch/hydra/issues/2902#issuecomment-2147121325
  # - override hydra/hydra_logging: disabled
  - override hydra/job_logging: none
  - _self_  # Allow defining variables at the top of this file

env:
  # use `dotenv.load_env()` to inject the environment
  # oc.env, see https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#oc-env
  # ???, see https://omegaconf.readthedocs.io/en/latest/usage.html#id20
  anthropic_api_key: "${oc.env:ANTHROPIC_API_KEY,???}"
  anthropic_base_url: "${oc.env:ANTHROPIC_BASE_URL,https://api.anthropic.com}"
  openai_api_key: "${oc.env:OPENAI_API_KEY,???}"
  openai_base_url: "${oc.env:OPENAI_BASE_URL,https://api.openai.com/v1}"
  newapi_api_key: "${oc.env:NEWAPI_API_KEY,???}"
  newapi_base_url: "${oc.env:NEWAPI_BASE_URL,???}"
  openrouter_api_key: "${oc.env:OPENROUTER_API_KEY,???}"
  openrouter_base_url: "${oc.env:OPENROUTER_BASE_URL,https://openrouter.ai/api/v1}"
  # points to where data is
  data_dir: "${oc.env:DATA_DIR,data/}"
  # configs for searching tool
  remove_snippets: "${oc.env:REMOVE_SNIPPETS,false}"
  remove_knowledge_graph: "${oc.env:REMOVE_KNOWLEDGE_GRAPH,false}"
  remove_answer_box: "${oc.env:REMOVE_ANSWER_BOX,false}"
  # whether using chinese context
  chinese_context: "${oc.env:CHINESE_CONTEXT,false}"

# Can define some top-level or default parameters here
project_name: "miroflow"
output_dir: logs/${benchmark.name}/${llm.provider_class}_${llm.model_name} 