site_name: MiroFlow

theme:
  name: material
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  locale: en
  # favicon: assets/m_logo.png

  features:
    - header.autohide
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables


repo_name: MiroFlow
repo_url: https://github.com/MiroMindAI/MiroFlow


nav:
  - 🏠 Introduction: 
    - News & Updates: index.md
    - License: license.md

  - 🚀 Quick Start:
    - Quickstart: quickstart.md
    - Core Concepts: core_concepts.md
    - YAML Configuration: yaml_config.md

  - "📊 Evaluation":
    - Overview: evaluation_overview.md
    - How to add new benchmarks: contribute_benchmarks.md
    - "": ""
    - "": ""
    - "": ""
    - "": ""
    - GAIA-Val:
      - Prepare Dataset: gaia_validation_prerequisites.md
      - Claude-3.7-Sonnet: gaia_validation_claude37sonnet.md
      - GPT-5: gaia_validation_gpt5.md
      - MiroThinker: gaia_validation_mirothinker.md
    - GAIA-Val-Text: gaia_validation_text_only.md
    - GAIA-Test: gaia_test.md
    - BrowseComp-EN: browsecomp_en.md
    - FutureX: futurex.md
    - xBench-DeepSearch: xbench_ds.md
    - FinSearchComp: finsearchcomp.md
    - HLE: hle.md
    - HLE-Text-Only: hle_text_only.md



  - 🔧 Tools: 
    - Overview: tool_overview.md
    - How to add new tools: contribute_tools.md
    - "": ""
    - "": ""
    - "": ""
    - "": ""
    - tool-reading: tool_reading.md
    - tool-searching: tool_searching.md
    - tool-searching-serper: tool_searching_serper.md
    - tool-audio: tool_audio.md
    - tool-audio-os: tool_audio_os.md
    - tool-reasoning: tool_reasoning.md
    - tool-reasoning-os: tool_reasoning_os.md
    - tool-image-video: tool_vqa.md
    - tool-image-video-os: tool_vqa_os.md
    - tool-python: tool_python.md
    - "": ""
    - "": ""
    - "": ""
    - "": ""
    - Advanced Features:
      - E2B Advanced Features: e2b_advanced_features.md
      - MiroAPI: miro_api.md

  - 🤖 LLM Clients: 
    - Overview: llm_clients_overview.md
    - How to add new LLM clients: contribute_llm_clients.md
    - "": ""
    - "": ""
    - "": ""
    - "": ""
    - MiroThinker: mirothinker.md
    - Claude 3.7 Sonnet (Official SDK): claude-3.7-sonnet.md
    - Claude 3.7 Sonnet (OpenRouter): openrouter-claude-3.7-sonnet.md
    - GPT-5: openai-gpt5.md
    - GPT-4o: openai-gpt4o.md

  - 📚 Resources: 
    - All About Agents: all_about_agents.md
    - Open Source Data: data.md
    - Applications: applications.md
    - FAQs: faqs.md
    - Contributors: contributors.md


extra:
  version:
    provider: mike